### PR TITLE
Add Microsoft bug bounty program

### PR DESCRIPTION
**Pull request by ngkogkos**
Hello,

As per title, adding an important asset that was missing.

### CODE REVIEW

**Comment by ngkogkos** [comment]
Screenshot showing that my PR submits a valid JSON:

image

**Comment by bauthard** [comment]
Hi @ngkogkos, 

This looks great add, a minor update, our API accepts only domain name as input, so can you update the domain list to only add root domain instead of subdomains. 

For example, 

```
live.com
```
instead of 

```
outlook.live.com
```

**Comment by ngkogkos** [comment]
Hi @bauthard thanks for the super quick review.

I've updated my PR as requested and removed an Azure parent domain that would probably lead to thousands of client subdomains with no benefit for the community.

Good job on this project, as a side suggestion, I think it will be good if the API can accept subdomains as well. A lot of programs/vendors enforce restrictions. From a performance perspective, you can avoid having to scan huge spaces if they are out of scope or host client assets.

**Comment by bauthard** [comment]
thanks @ngkogkos, that shouldn't be an issue as we are collecting passing data only.

**Pull request merged**
